### ISSUE TITLE
why are u being a bum

### ISSUE THREAD

**Issue by adithya-gv** [JIceberg/CLRS-Exercises#1]
:rie:

**Comment by JIceberg** [comment]
Well that's not very professional, is it?

**Comment by adithya-gv** [comment]
neither is your commit message

**Comment by JIceberg** [comment]
You deserve it.

**Comment by adithya-gv** [comment]
then change it back :)

**Comment by JIceberg** [comment]
![](https://cdn.discordapp.com/emojis/669214632556363816.png?v=1)
No.

**Comment by adithya-gv** [comment]
thank you for your service jackson.
